In [1]:
import os
import sqlite3
import pandas as pd

In [2]:
print(os.getcwd())

c:\Users\salit\OneDrive\Escritorio\TB\GitHub\whiteberry\parte1

In [3]:
connection = sqlite3.connect("sql-murder-mystery.db")

cursor = connection.cursor()

In [4]:
##  to find the names of the tables in this database
pd.read_sql("""
    SELECT name 
    FROM sqlite_master
    WHERE type = 'table'
""", connection)

                     name
0      crime_scene_report
1         drivers_license
2                  person
3  facebook_event_checkin
4               interview
5      get_fit_now_member
6    get_fit_now_check_in
7                  income
8                solution

In [5]:
# find the structure of the `crime_scene_report` table
cursor.execute("""
    SELECT sql 
    FROM sqlite_master
    WHERE name = 'crime_scene_report'
""")

print(cursor.fetchone())

('CREATE TABLE crime_scene_report (\n        date integer,\n        type text,\n        description text,\n        city text\n    )',)

In [6]:
# 1 query inicial pra buscar crímenes cometidos el 15 de enero de 2018 en sql City
cursor.execute("""
SELECT * FROM crime_scene_report WHERE date = 20180115  AND type = 'murder' AND city = 'SQL City'""")


# para que muestre la descripción entera, si no se corta
pd.set_option('display.max_colwidth', None)
df_1

df_1 = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])
df_1

NameError: name 'df_1' is not defined

In [ ]:
# 2 Persona que vive en el último número de Northwestern Dr
cursor.execute("""
SELECT *  
FROM person p
JOIN (
    SELECT MAX(address_number) AS max_val
    FROM person
    WHERE address_street_name = 'Northwestern Dr'
) x
ON p.address_number = x.max_val
WHERE p.address_street_name = 'Northwestern Dr'""")

df_2 = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])
df_2
### id person = 14887

,id,name,license_id,address_number,address_street_name,ssn,max_val
0,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949,4919

In [ ]:
#3  Personas que viven en el último número de Northwestern Dr y en Franklin Ave
cursor.execute("""
SELECT * FROM person WHERE address_street_name LIKE "%Franklin Ave%" OR id = 14887""")

df_3 = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])
df_3

,id,name,license_id,address_number,address_street_name,ssn
0,12207,Wilmer Wolever,509484,139,Franklin Ave,636825374
1,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949
2,16371,Annabel Miller,490173,103,Franklin Ave,318771143
3,17683,Johnnie Schee,968887,1277,Franklin Ave,815977821
4,18651,Carleen Etoll,356746,22,Franklin Ave,193369255
5,22636,Zachary Ybarbo,768359,785,Franklin Ave,285346605
6,24737,Gema Nantz,273410,3968,Franklin Ave,180545802
7,30654,Clarita Rickels,418084,2254,Franklin Ave,714941023
8,32264,Shelby Dezeeuw,735415,1391,Franklin Ave,143197463
9,33793,Amado Mattan,161915,99,Franklin Ave,125205748
10,34592,Cordell Lindamood,592762,3657,Franklin Ave,509890333
11,36328,Domenic Laun,971080,3809,Franklin Ave,825329637
12,36400,Noe Pancoast,895755,3443,Franklin Ave,732212073
13,37616,Katelyn Schwerin,430143,332,Franklin Ave,392365033
14,46827,Bev Billiter,643591,2316,Franklin Ave,940192302
15,52059,Jordan Pelton,686854,2786,Franklin Ave,676224073
16,52075,Ezra Phy,928109,384,Franklin Ave,176404498
17,52121,Yelena Whitler,427830,3185,Franklin Ave,115106155
18,54817,Guy Bustard,213929,591,Franklin Ave,820850670
19,54896,Patty Wamsley,688488,1097,Franklin Ave,725272037
20,56142,William Shiver,741336,1926,Franklin Ave,219913461
21,57051,Lavette Koehl,137365,2284,Franklin Ave,776046786
22,59746,Ronny Gumbert,469722,3197,Franklin Ave,561067477
23,60944,Ricki Bidding,443364,2072,Franklin Ave,614976330
24,61001,Laurine Bousman,197150,247,Franklin Ave,431360364
25,61437,Colette Hollomon,661377,453,Franklin Ave,314956038
26,62292,Isaiah Holsten,913856,747,Franklin Ave,995368430
27,62520,Mariah Lepetich,450447,3086,Franklin Ave,797745632
28,67292,Renita Roperto,801041,625,Franklin Ave,894442480
29,69719,Hope Arzabala,311724,841,Franklin Ave,270289620
30,70050,Whitney Herkenratt,138462,3445,Franklin Ave,552518972
31,75510,Sebastian Ramnarase,333188,1127,Franklin Ave,315716580
32,76128,Ressie Razze,633497,1199,Franklin Ave,456366143
33,78170,Graig Summy,192325,3387,Franklin Ave,277793306
34,78408,Dante Eschen,218173,3447,Franklin Ave,135374633
35,78658,Blake Chrones,310242,2014,Franklin Ave,423048084
36,78830,Candice Train,814779,3255,Franklin Ave,717570815
37,83003,Wilmer Casella,672050,3564,Franklin Ave,569057540
38,83754,Maria Walsh,201334,2716,Franklin Ave,121282864
39,84531,Edgar Mendieta,315790,3881,Franklin Ave,458847132
40,87521,Moses Ikerd,638991,2283,Franklin Ave,797715435
41,88966,Raul Eads,570927,2066,Franklin Ave,764132739
42,93947,Omer Andreoni,605718,13,Franklin Ave,322594288
43,95119,Hong Lisa,825828,375,Franklin Ave,113438176
44,97913,Cameron Dilick,971988,2954,Franklin Ave,665147939
45,98744,Jordan Myntti,256116,3104,Franklin Ave,876030104

In [ ]:
# 4 Entrevistas de los testigos posibles testigos (personas cuyo id están entre las personas que viven n el último número de Northwestern Dr y en Franklin Ave)
cursor.execute("""
SELECT * FROM interview WHERE person_id IN (SELECT id FROM person WHERE address_street_name LIKE "%Franklin Ave%" OR id = 14887)""")
df_4 = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])
df_4

,person_id,transcript
0,33793,wood--(she considered him to be a footman because he was in livery:\n
1,88966,like them raw.’\n
2,67292,\n
3,62292,\n
4,83003,"An enormous puppy was looking down at her with large round eyes, and\n"
5,95119,"So she sat on, with closed eyes, and half believed herself in\n"
6,61001,with a smile. There was a dead silence.\n
7,22636,\n
8,60944,"Lastly, she pictured to herself how this same little sister of hers\n"
9,84531,"way?’, holding her hand on the top of her head to feel which way it was\n"
10,37616,"‘Oh, PLEASE mind what you’re doing!’ cried Alice, jumping up and down in\n"
11,78658,both go to\n
12,24737,\n
13,93947,"‘I haven’t the least idea what you’re talking about,’ said Alice.\n"
14,59746,now! How puzzling all these changes are! I’m never sure what I’m going\n
15,61437,heavy sobs.\n
16,34592,‘How do you like the Queen?’ said the Cat in a low voice.\n
17,62520,\n
18,12207,\n
19,75510,"It was, no doubt: only Alice did not like to be told so. ‘It’s really\n"
20,32264,"to play croquet.’ The Frog-Footman repeated, in the same solemn tone,\n"
21,54817,\n
22,52121,"place, with a little house in it about four feet high. ‘Whoever lives\n"
23,46827,\n
24,36328,"‘You may not have lived much under the sea--’ [‘I haven’t,’ said\n"
25,78170,"And the muscular strength, which it gave to my jaw,\n"
26,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership number on the bag started with ""48Z"". Only gold members have those bags. The man got into a car with a plate that included ""H42W""."
27,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th."

In [ ]:
# 5 entrevistas a testigos junto con datos de los testigos que viven en el último número de farankiln ave or ultimo numero de Northwestern dr
cursor.execute("""
SELECT i.*, p.* FROM interview i
left join person p
on i.person_id = p.id
WHERE i.person_id IN (SELECT id FROM person WHERE address_street_name LIKE "%Franklin Ave%" OR id = 14887)""")
df_5 = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])
df_5

# 16371

,person_id,transcript,id,name,license_id,address_number,address_street_name,ssn
0,33793,wood--(she considered him to be a footman because he was in livery:\n,33793,Amado Mattan,161915,99,Franklin Ave,125205748
1,88966,like them raw.’\n,88966,Raul Eads,570927,2066,Franklin Ave,764132739
2,67292,\n,67292,Renita Roperto,801041,625,Franklin Ave,894442480
3,62292,\n,62292,Isaiah Holsten,913856,747,Franklin Ave,995368430
4,83003,"An enormous puppy was looking down at her with large round eyes, and\n",83003,Wilmer Casella,672050,3564,Franklin Ave,569057540
5,95119,"So she sat on, with closed eyes, and half believed herself in\n",95119,Hong Lisa,825828,375,Franklin Ave,113438176
6,61001,with a smile. There was a dead silence.\n,61001,Laurine Bousman,197150,247,Franklin Ave,431360364
7,22636,\n,22636,Zachary Ybarbo,768359,785,Franklin Ave,285346605
8,60944,"Lastly, she pictured to herself how this same little sister of hers\n",60944,Ricki Bidding,443364,2072,Franklin Ave,614976330
9,84531,"way?’, holding her hand on the top of her head to feel which way it was\n",84531,Edgar Mendieta,315790,3881,Franklin Ave,458847132
10,37616,"‘Oh, PLEASE mind what you’re doing!’ cried Alice, jumping up and down in\n",37616,Katelyn Schwerin,430143,332,Franklin Ave,392365033
11,78658,both go to\n,78658,Blake Chrones,310242,2014,Franklin Ave,423048084
12,24737,\n,24737,Gema Nantz,273410,3968,Franklin Ave,180545802
13,93947,"‘I haven’t the least idea what you’re talking about,’ said Alice.\n",93947,Omer Andreoni,605718,13,Franklin Ave,322594288
14,59746,now! How puzzling all these changes are! I’m never sure what I’m going\n,59746,Ronny Gumbert,469722,3197,Franklin Ave,561067477
15,61437,heavy sobs.\n,61437,Colette Hollomon,661377,453,Franklin Ave,314956038
16,34592,‘How do you like the Queen?’ said the Cat in a low voice.\n,34592,Cordell Lindamood,592762,3657,Franklin Ave,509890333
17,62520,\n,62520,Mariah Lepetich,450447,3086,Franklin Ave,797745632
18,12207,\n,12207,Wilmer Wolever,509484,139,Franklin Ave,636825374
19,75510,"It was, no doubt: only Alice did not like to be told so. ‘It’s really\n",75510,Sebastian Ramnarase,333188,1127,Franklin Ave,315716580
20,32264,"to play croquet.’ The Frog-Footman repeated, in the same solemn tone,\n",32264,Shelby Dezeeuw,735415,1391,Franklin Ave,143197463
21,54817,\n,54817,Guy Bustard,213929,591,Franklin Ave,820850670
22,52121,"place, with a little house in it about four feet high. ‘Whoever lives\n",52121,Yelena Whitler,427830,3185,Franklin Ave,115106155
23,46827,\n,46827,Bev Billiter,643591,2316,Franklin Ave,940192302
24,36328,"‘You may not have lived much under the sea--’ [‘I haven’t,’ said\n",36328,Domenic Laun,971080,3809,Franklin Ave,825329637
25,78170,"And the muscular strength, which it gave to my jaw,\n",78170,Graig Summy,192325,3387,Franklin Ave,277793306
26,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership number on the bag started with ""48Z"". Only gold members have those bags. The man got into a car with a plate that included ""H42W"".",14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949
27,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.",16371,Annabel Miller,490173,103,Franklin Ave,318771143

In [ ]:
# 7 eventos el día del crimen en los que el asistente no era testigo
cursor.execute("""
SELECT f.*, p.* FROM facebook_event_checkin f
LEFT JOIN person p
ON p.id = f.person_id  
WHERE f.event_id = 4719
AND f.date = 20180115
AND p.id NOT IN(SELECT id FROM person WHERE address_street_name LIKE "%Franklin Ave%" OR id = 14887)""")

df_6 = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])
df_6
# persons id tres 14887(testigo), 16371 (es el segundo testigo deducible por la dirección ) 67318 Jeremy Bowers el malo

,person_id,event_id,event_name,date,id,name,license_id,address_number,address_street_name,ssn
0,67318,4719,The Funky Grooves Tour,20180115,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279

In [ ]:
## check the solution 

cursor.execute("INSERT INTO solution VALUES (1, 'Jeremy Bowers')")
connection.commit()

In [ ]:
cursor.execute("SELECT value FROM solution")
pd.DataFrame(cursor.fetchall(), columns=["value"])

                                                                                                                                                                                                                                                                                                                                                                                                value
0  Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge, try querying the interview transcript of the murderer to find the real villain behind this crime. If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries. Use this same INSERT statement with your new suspect to check your answer.

In [ ]:
# la transcripción del primer sospechoso

cursor.execute("""
SELECT transcript FROM interview 
WHERE person_id = 67318
""")

df_7 = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])
print(df_7['transcript'][0])

I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.

In [ ]:
cursor.execute("""
SELECT p.name, p.id
FROM person p
JOIN drivers_license dl ON p.license_id = dl.id
JOIN facebook_event_checkin fb ON p.id = fb.person_id
WHERE dl.hair_color = 'red'
AND dl.gender = 'female'
AND dl.height BETWEEN 65 AND 67
AND dl.car_make = 'Tesla'
AND dl.car_model = 'Model S'
AND fb.event_name = 'SQL Symphony Concert'
AND fb.date BETWEEN 20171201 AND 20171231
GROUP BY p.id
HAVING COUNT(fb.event_name) = 3
""")

df_villain = pd.DataFrame(cursor.fetchall(), columns=[desc[0] for desc in cursor.description])
df_villain

               name     id
0  Miranda Priestly  99716

In [ ]:
## check the solution v2

cursor.execute("INSERT INTO solution VALUES (1, 'Miranda Priestly')")
connection.commit()

In [ ]:
cursor.execute("SELECT value FROM solution")
pd.DataFrame(cursor.fetchall(), columns=["value"])

                                                                                                                                                          value
0  Congrats, you found the brains behind the murder! Everyone in SQL City hails you as the greatest SQL detective of all time. Time to break out the champagne!

**El asesino material del crimen es Jeremy Bowers**  
**La autora intelectual del crimen es Miranda Priestly**